deps.edn, src/main/com/wsscode/pathom3/connect/planner.cljc, src/main/com/wsscode/pathom3/interface/smart_map.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc
=> Babashka smart maps

deps.edn, src/main/com/wsscode/pathom3/connect/planner.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc, test/com/wsscode/pathom3/generative_tests/execution.cljc
Initial progress to support nested queries generation. This one adds the simple case of a nested request at root. Not very useful yet.
=> Generative nested queries

src/main/com/wsscode/pathom3/connect/planner.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc
from https://github.com/wilkerlucio/pathom/issues/192
=> Fix partial cycles planning

.clj-kondo/config.edn, src/main/com/wsscode/pathom3/connect/built_in/plugins.cljc, src/main/com/wsscode/pathom3/connect/planner.cljc, src/main/com/wsscode/pathom3/connect/runner.cljc, src/main/com/wsscode/pathom3/connect/runner/async.cljc, src/main/com/wsscode/pathom3/connect/runner/stats.cljc, src/main/com/wsscode/pathom3/error.cljc, src/main/com/wsscode/pathom3/interface/smart_map.cljc, src/main/com/wsscode/pathom3/plugin.cljc, test/com/wsscode/pathom3/connect/built_in/plugins_test.cljc, test/com/wsscode/pathom3/connect/runner/stats_test.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc, test/com/wsscode/pathom3/error_test.cljc, test/com/wsscode/pathom3/plugin_test.cljc
Closes #47 
New docs for attribute errors at: https://pathom3.wsscode.com/docs/error-handling
=> Attribute errors

.clj-kondo/config.edn, CHANGELOG.md, resources/clj-kondo.exports/com.wsscode/pathom3/config.edn, src/main/com/wsscode/pathom3/connect/built_in/plugins.cljc, src/main/com/wsscode/pathom3/connect/foreign.cljc, src/main/com/wsscode/pathom3/connect/indexes.cljc, src/main/com/wsscode/pathom3/connect/planner.cljc, src/main/com/wsscode/pathom3/connect/runner.cljc, src/main/com/wsscode/pathom3/connect/runner/async.cljc, src/main/com/wsscode/pathom3/error.cljc, src/main/com/wsscode/pathom3/format/eql.cljc, src/main/com/wsscode/pathom3/format/shape_descriptor.cljc, src/main/com/wsscode/pathom3/interface/async/eql.cljc, src/main/com/wsscode/pathom3/interface/eql.cljc, src/main/com/wsscode/pathom3/interface/smart_map.cljc, src/main/com/wsscode/pathom3/system.cljc, src/promesa/com/wsscode/promesa/macros.cljc, test/com/wsscode/pathom3/connect/built_in/plugins_test.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc, test/com/wsscode/pathom3/error_test.cljc, test/com/wsscode/pathom3/format/eql_test.cljc, test/com/wsscode/pathom3/format/shape_descriptor_test.cljc, test/com/wsscode/pathom3/interface/eql_test.cljc, test/com/wsscode/promesa/macros_test.clj
This PR will make Pathom use a strict mode by default, which will cause failures to happen earlier.
Discussion around these changes are happening at #65 
Input is welcome, everything here still subject to change before merging.
Closes #69
=> Strict mode

src/main/com/wsscode/pathom3/connect/planner.cljc, src/main/com/wsscode/pathom3/connect/runner.cljc, src/main/com/wsscode/pathom3/connect/runner/async.cljc, src/main/com/wsscode/pathom3/format/eql.cljc, src/main/com/wsscode/pathom3/format/shape_descriptor.cljc, test/com/wsscode/pathom3/connect/foreign_test.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc, test/com/wsscode/pathom3/format/eql_test.cljc, test/com/wsscode/pathom3/format/shape_descriptor_test.cljc
=> Foreign unions

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/planner.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc
=> Nested cycles

deps.edn, pom.xml, src/main/com/wsscode/pathom3/error.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc, test/com/wsscode/pathom3/test/helpers.cljc
=> Consistent error cases

CHANGELOG.md, deps.edn, src/main/com/wsscode/pathom3/connect/planner.cljc, src/main/com/wsscode/pathom3/format/shape_descriptor.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc, test/com/wsscode/pathom3/format/shape_descriptor_test.cljc, test/com/wsscode/pathom3/test/helpers.cljc
=> Dynamic nested params

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/planner.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc
=> Fix nested dependency process

CHANGELOG.md, pom.xml, src/main/com/wsscode/pathom3/connect/runner.cljc, src/main/com/wsscode/pathom3/connect/runner/async.cljc, src/main/com/wsscode/pathom3/connect/runner/parallel.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc
=> Batch split params

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/runner.cljc, src/main/com/wsscode/pathom3/connect/runner/async.cljc, src/main/com/wsscode/pathom3/connect/runner/parallel.cljc, src/main/com/wsscode/pathom3/format/shape_descriptor.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc, test/com/wsscode/pathom3/format/shape_descriptor_test.cljc
=> Improve performance on input shape check

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/built_in/plugins.cljc, src/main/com/wsscode/pathom3/connect/runner.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc
=> Add weight sort feature to load balance between OR branches

CHANGELOG.md, deps.edn, src/main/com/wsscode/pathom3/connect/planner.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc
=> Optimize nested AND branches on planner

CHANGELOG.md, src/main/com/wsscode/pathom3/format/shape_descriptor.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc, test/com/wsscode/pathom3/format/shape_descriptor_test.cljc
=> Fix issue #152 missing shape check when data value is nil

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/planner.cljc, src/main/com/wsscode/pathom3/format/shape_descriptor.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc, test/com/wsscode/pathom3/format/shape_descriptor_test.cljc
=> Fix placeholder nodes on dynamic resolvers

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/runner.cljc, src/main/com/wsscode/pathom3/format/eql.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc, test/com/wsscode/pathom3/format/eql_test.cljc
=> Issue 176 map container

CHANGELOG.md, pom.xml, src/main/com/wsscode/pathom3/connect/planner.cljc, src/main/com/wsscode/pathom3/format/eql.cljc, test/com/wsscode/pathom3/connect/planner_test.cljc, test/com/wsscode/pathom3/format/eql_test.cljc
=> Disregard ident values on cache keys for the planner

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/operation.cljc, test/com/wsscode/pathom3/connect/operation_test.cljc
=> Fix name reporting on invalid config for resolvers and mutations

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/runner.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc
=> Fix missing data on nested batches

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/planner.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc
=> Fix planning issue when optimizing `OR` subpaths

CHANGELOG.md, pom.xml, src/main/com/wsscode/pathom3/connect/built_in/plugins.cljc, src/main/com/wsscode/pathom3/connect/foreign.cljc, src/main/com/wsscode/pathom3/connect/runner.cljc, test/com/wsscode/pathom3/connect/built_in/plugins_test.cljc, test/com/wsscode/pathom3/connect/foreign_test.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc
=> Placeholders won't override entity data via params by default

CHANGELOG.md, src/main/com/wsscode/pathom3/interface/async/eql.cljc, src/main/com/wsscode/pathom3/interface/eql.cljc, test/com/wsscode/pathom3/interface/async/eql_test.clj, test/com/wsscode/pathom3/interface/eql_test.cljc
=> Mike706574 main

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/operation.cljc, test/com/wsscode/pathom3/connect/operation_test.cljc
=> Support `applyTo` on resolvers and mutations (issue #203)

CHANGELOG.md, src/main/com/wsscode/pathom3/connect/runner/parallel.cljc
=> Run idents in parallel

CHANGELOG.md, src/main/com/wsscode/pathom3/format/shape_descriptor.cljc, test/com/wsscode/pathom3/connect/runner_test.cljc
=> Fix wrong input order on nested resolvers
